# create a manual trigger
name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        description: 'A environment passed from the caller workflow'
        default: 'dev'
        required: false
        type: string
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SP_DETAILS }}

      - name: Step 1
        run: echo "az deployment group create --resource-group ${{ vars.RESOURCE_GROUP }} --template-file ./InfrastructureAsCode/main.bicep"

      - name: Deploy to Azure
        uses: azure/CLI@v1
        with:
          azcliversion: 2.51.0
          inlineScript: |
            az deployment group create --resource-group ${{ vars.RESOURCE_GROUP }} --template-file ./InfrastructureAsCode/main.bicep --parameters environment=${{ github.event.inputs.environment }}
